# Generated by Django 4.2.18 on 2025-01-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagine',
            new_name='image',
        ),
    ]
